before_script:
    ##
    ## Install ssh-agent if not already installed, it is required by Docker.
    ## (change apt-get to yum if you use an RPM-based image)
    ##
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'

    ##
    ## Run ssh-agent (inside the build environment)
    ##
  - eval $(ssh-agent -s)
  - mkdir -p ~/.ssh
  - echo "$SSH_DEPLOYER_PRIVATE_KEY" > ~/.ssh/id_rsa
  - chmod 700 ~/.ssh/id_rsa
  - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts

build:
  stage: build
  only:
    - stage
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull  -t "$CI_REGISTRY_IMAGE":stage .
    - docker push "$CI_REGISTRY_IMAGE":stage
  services:
    - docker:dind

deploy:
  stage: deploy
  only:
    - stage
  script:
    - ssh -o StrictHostKeyChecking=no deployer@dev3.ingenix.ai docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - ssh -o StrictHostKeyChecking=no deployer@dev3.ingenix.ai "cd /opt/servers/ && docker-compose -f docker-compose-w12-stage.yml pull && docker-compose -f docker-compose-w12-stage.yml up -d"
