# jobs
defaults: &defaults
  docker:
    - image: docker:dind
  working_directory: ~/code

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: pull submodules
          command: |
              apk add --no-cache git
              git submodule sync --recursive
              git submodule update --init --recursive
      - run:
          name: build image
          command: |
              docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
              docker build --pull  -t "$DOCKERHUB_USERNAME/$CI_REGISTRY_IMAGE:stage" .
              docker push "$DOCKERHUB_USERNAME/$CI_REGISTRY_IMAGE:stage"
  deploy:
    <<: *defaults
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: setup
          command: |
            apk add --no-cache openssh-client
            eval $(ssh-agent -s)
      - run:
          name: deploy
          command: |
            ssh -o StrictHostKeyChecking=no "$DEPLOY_USER_STAGE@$DEPLOY_SERVER_STAGE" docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD"
            ssh -o StrictHostKeyChecking=no "$DEPLOY_USER_STAGE@$DEPLOY_SERVER_STAGE" "cd /opt/servers/ && docker-compose -f docker-compose-w12-stage.yml pull && docker-compose -f docker-compose-w12-stage.yml up -d"

# workflows
default_filters: &default_filters
  filters:
    branches:
      only:
        - stage

workflows:
  version: 2
  build_deploy:
    jobs:
      - build:
          <<: *default_filters
      - deploy:
          <<: *default_filters
          requires:
            - build
